### ISSUE TITLE
Failed to activate the java-plus package

### ISSUE THREAD

**Issue by ghost** [noseglid/java-plus#1]
### Description of issue:
I have installed this package manually with the .zip file, and I have got the following error about a missing module whenever I try to activate the plugin.

This error shows up on both Atom 1.15.0 and 1.16.0.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint 18.1 Serena
**Thrown From**: [java-plus](https://github.com/noseglid/java-plus) package 0.1.0

### Stack Trace

Failed to activate the java-plus package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/java-plus-0.1.0/lib/java-plus.js:6:5)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Non-Core Packages

```
atom-java-snippets 0.5.1 
java-class-complete 0.0.6 
java-generator-plus 2.6.0 
java-plus 0.1.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
terminal-panel 1.14.1 
```

**Comment by noseglid** [comment]
You should install it via the package manager inside `Atom`.
Alternatively you could run `apm install java-plus` in a terminal.
